# Generated by Django 5.1.4 on 2024-12-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0003_alter_flashcard_question_flashcardset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='flashcard_set',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard_app.flashcardset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
