# Generated by Django 5.1.4 on 2024-12-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0004_remove_flashcard_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='back',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='front',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard_app.flashcardset'),
        ),
    ]
