# Generated by Django 5.1.4 on 2024-12-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0005_rename_back_flashcard_answer_remove_flashcard_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardset',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='set',
        ),
        migrations.RemoveField(
            model_name='flashcardset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flashcardset',
            name='created_by',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard_app.flashcardset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(),
        ),
    ]
